# docker-compose.production.yml

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
	    interval: 5s
        timeout: 5s
        retries: 5
        
  backend:
    image: kolesnikyi/taski_backend # Качаем с Docker Hub
    env_file: .env
    volumes:
      - static:/backend_static
    depends_on:
      db:
        condition: service_healthy        
  
  frontend:
    image: kolesnikyi/taski_frontend # Качаем с Docker Hub
    env_file: .env
    volumes:
      - static:/frontend_static

  gateway:
    image: kolesnikyi/taski_gateway # Качаем с Docker Hub
    env_file: .env
    volumes:
      - static:/staticfiles
    ports:
      - 8000:80 
    depends_on:
      - backend
      - frontend
